version: '3.3'
networks:
  default:
    name: media

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $CONFIG_DIR/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $CONFIG_DIR/radarr:/config
      - $MEDIA_DIR:/media:/media
      - $MEDIA_DIR/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $CONFIG_DIR/sonarr:/config
      - $MEDIA_DIR:/media:/media
      - $MEDIA_DIR/downloads:/downloads
    ports:
      - 8989:8989  
    restart: unless-stopped
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $CONFIG_DIR/jellyfin:/config
      - $MEDIA_DIR/series:/data/tvshows
      - $MEDIA_DIR/movies:/data/movies
    ports:
      - 8096:8096
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $CONFIG_DIR/qbittorrent:/config
      - $MEDIA_DIR/downloads:/downloads
      - $MEDIA_DIR/media:/media
    ports:
      - 8080:8080
    restart: unless-stopped
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $CONFIG_DIR/flaresolverr:/config
    ports:
      - 8191:8191
    restart: unless-stopped
